<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RLE0131" name="Community" tests="1" failures="1" timestamp="29 Dec 2015 11:07:30 GMT" time="23.804" errors="0">
  <testcase name="checkValidUser" time="23.794" classname="com.community.scholastic.test.CommunityLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Sign in now.] but found [Sign in no]">
      <![CDATA[java.lang.AssertionError: expected [Sign in now.] but found [Sign in no]
	at com.community.scholastic.test.CommunityLoginTest.checkValidUser(CommunityLoginTest.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkValidUser -->
</testsuite> <!-- Community -->
